import { MembershipPlan, WorkoutProgram, Trainer, GalleryItem, GymSettings, MembershipEnquiry, ContactMessage } from './types';

export const initialSettings: GymSettings = {
  gymName: 'GYM',
  whatsappNumber: '03417885841',
  displayPhone: '+92 341 7885841',
  email: 'info@gymfitness.pk',
  address: 'Plot 42-B, Commercial Avenue, Main Boulevard',
  city: 'Lahore, Pakistan',
  openingHoursWeekday: 'Mon - Sat: 6:00 AM - 11:00 PM',
  openingHoursSunday: 'Sunday: 8:00 AM - 8:00 PM',
  currency: 'Rs.',
  heroHeadline: 'BE STRONGER THAN YOUR EXCUSES',
  heroSubtitle: 'Build your body. Build your confidence.',
  heroDescription: 'Join our gym and transform your body with expert trainers, modern equipment and personalized fitness programs.',
};

export const initialPlans: MembershipPlan[] = [
  {
    id: 'plan-basic',
    name: 'BASIC PLAN',
    price: 999,
    period: 'Month',
    isPopular: false,
    description: 'Ideal for beginners and fitness enthusiasts seeking essential gym access.',
    features: [
      'Full Gym Access',
      'Basic Strength & Cardio Equipment',
      'Locker Room & Shower Access',
      'Free Fitness Consultation',
      'Flexible Monthly Renewal',
    ],
  },
  {
    id: 'plan-standard',
    name: 'STANDARD PLAN',
    price: 1499,
    period: 'Month',
    isPopular: true,
    description: 'Our most popular plan designed to accelerate results with trainer support.',
    features: [
      'Unlimited Gym Access',
      'All Modern Equipment & Free Weights',
      'Personal Trainer (2 Sessions)',
      'Customized Diet & Nutrition Plan',
      'Locker Room & Steam Bath Access',
      'Weekly Body Composition Check',
    ],
  },
  {
    id: 'plan-premium',
    name: 'PREMIUM PLAN',
    price: 2499,
    period: 'Month',
    isPopular: false,
    description: 'Comprehensive VIP fitness package with group classes and dedicated coaching.',
    features: [
      '24/7 Priority Gym Access',
      'All Heavy Strength & Functional Equipment',
      'Personal Trainer (4 Sessions)',
      'Customized Diet & Supplement Guide',
      'Unlimited Group Workout Classes',
      'Dedicated Locker & Sauna Access',
      'WhatsApp Trainer Support 24/7',
    ],
  },
];

export const initialPrograms: WorkoutProgram[] = [
  {
    id: 'prog-muscle',
    name: 'Muscle Building',
    tagline: 'Build strength and gain lean muscle mass.',
    description: 'Scientifically backed hypertrophy protocols, progressive overload guidance, and state-of-the-art strength training machines to maximize muscle growth.',
    image: '/images/hero.jpg',
    duration: '12 Weeks Protocol',
    level: 'Beginner to Advanced',
    features: [
      'Modern strength training equipment',
      'Compound lifts & isolation techniques',
      'Targeted muscle recovery guidance',
      'Personalized volume tracking',
    ],
    trainerName: 'Bilal Ahmed',
  },
  {
    id: 'prog-weightloss',
    name: 'Weight Loss',
    tagline: 'Lose weight and improve cardiovascular fitness.',
    description: 'High-energy caloric burn sessions combining metabolic conditioning, treadmill sprints, rowing, and tailored nutritional coaching to shed fat safely.',
    image: '/images/program.jpg',
    duration: '8 Weeks Transformation',
    level: 'All Fitness Levels',
    features: [
      'Cardio & personalized workout plans',
      'High-Intensity Interval Training (HIIT)',
      'Fat-loss nutrition plan included',
      'Bi-weekly progress body scans',
    ],
    trainerName: 'Hamza Ali',
  },
  {
    id: 'prog-strength',
    name: 'Strength Training',
    tagline: 'Increase functional power and athletic endurance.',
    description: 'Master powerlifting essentials (squat, bench, deadlift) and functional athletic movements using certified Olympic barbells and bumper plates.',
    image: '/images/about.jpg',
    duration: '10 Weeks Program',
    level: 'Intermediate to Advanced',
    features: [
      'Progressive strength workouts',
      'Form & posture correction',
      'Power racks and Olympic platforms',
      'Core stability & injury prevention',
    ],
    trainerName: 'Tariq Khan',
  },
  {
    id: 'prog-yoga',
    name: 'Yoga & Flexibility',
    tagline: 'Improve flexibility, mobility, and reduce stress.',
    description: 'Enhance joint range of motion, muscle elasticity, and mental calmness through structured Vinyasa flow, deep stretching, and breathing exercises.',
    image: '/images/about.jpg',
    duration: 'Ongoing Classes',
    level: 'All Levels Welcomed',
    features: [
      'Full body mobility flows',
      'Post-workout recovery stretching',
      'Mind-body stress reduction',
      'Morning & evening slots available',
    ],
    trainerName: 'Zainab Malik',
  },
];

export const initialTrainers: Trainer[] = [
  {
    id: 'trainer-1',
    name: 'Tariq Khan',
    speciality: 'Strength & Powerlifting Coach',
    experience: '8+ Years Experience',
    image: '/images/trainer1.jpg',
    bio: 'Certified CSCS strength coach specialized in power lifting mechanics, functional hypertrophy, and athletic conditioning.',
    socials: {
      instagram: 'https://instagram.com',
      facebook: 'https://facebook.com',
      whatsapp: '03417885841',
    },
  },
  {
    id: 'trainer-2',
    name: 'Hamza Ali',
    speciality: 'Weight Loss & HIIT Specialist',
    experience: '6+ Years Experience',
    image: '/images/hero.jpg',
    bio: 'Passionate about rapid fat loss transformations, conditioning circuits, and sustainable healthy habits that stick.',
    socials: {
      instagram: 'https://instagram.com',
      facebook: 'https://facebook.com',
      whatsapp: '03417885841',
    },
  },
  {
    id: 'trainer-3',
    name: 'Zainab Malik',
    speciality: 'Yoga & Mobility Instructor',
    experience: '5+ Years Experience',
    image: '/images/about.jpg',
    bio: 'Certified 500-hour RYT yoga instructor focusing on posture alignment, core activation, flexibility, and athletic recovery.',
    socials: {
      instagram: 'https://instagram.com',
      facebook: 'https://facebook.com',
      whatsapp: '03417885841',
    },
  },
  {
    id: 'trainer-4',
    name: 'Bilal Ahmed',
    speciality: 'Hypertrophy & Physique Coach',
    experience: '7+ Years Experience',
    image: '/images/program.jpg',
    bio: 'National physique competitor helping athletes and everyday champions build symmetrical, aesthetic, and functional muscle.',
    socials: {
      instagram: 'https://instagram.com',
      facebook: 'https://facebook.com',
      whatsapp: '03417885841',
    },
  },
];

export const initialGallery: GalleryItem[] = [
  {
    id: 'gal-1',
    title: 'Modern Power Rack Zone',
    category: 'equipment',
    image: '/images/about.jpg',
  },
  {
    id: 'gal-2',
    title: 'Free Weights & Dumbbells Arena',
    category: 'equipment',
    image: '/images/hero.jpg',
  },
  {
    id: 'gal-3',
    title: 'Intense Strength Training',
    category: 'training',
    image: '/images/program.jpg',
  },
  {
    id: 'gal-4',
    title: 'Cardio Suite & Treadmills',
    category: 'cardio',
    image: '/images/about.jpg',
  },
  {
    id: 'gal-5',
    title: 'Spacious Gym Floor Interior',
    category: 'interior',
    image: '/images/about.jpg',
  },
  {
    id: 'gal-6',
    title: 'Personal Training Session',
    category: 'training',
    image: '/images/trainer1.jpg',
  },
];

export const initialEnquiries: MembershipEnquiry[] = [
  {
    id: 'enq-1',
    enquiryNumber: 'GYM-PK-4921',
    fullName: 'Ahmed Raza',
    phoneNumber: '03001234567',
    planId: 'plan-standard',
    planName: 'STANDARD PLAN',
    planPrice: 1499,
    age: 26,
    joiningDate: '2026-10-10',
    notes: 'Interested in evening timings after 6 PM.',
    status: 'Contacted',
    createdAt: '2026-10-04 14:32',
  },
  {
    id: 'enq-2',
    enquiryNumber: 'GYM-PK-7812',
    fullName: 'Usman Farooq',
    phoneNumber: '03219876543',
    planId: 'plan-premium',
    planName: 'PREMIUM PLAN',
    planPrice: 2499,
    age: 31,
    joiningDate: '2026-10-08',
    notes: 'Wants personal training for muscle building.',
    status: 'New',
    createdAt: '2026-10-05 09:15',
  },
  {
    id: 'enq-3',
    enquiryNumber: 'GYM-PK-3209',
    fullName: 'Fatima Noor',
    phoneNumber: '03335551234',
    planId: 'plan-standard',
    planName: 'STANDARD PLAN',
    planPrice: 1499,
    age: 23,
    joiningDate: '2026-10-12',
    notes: 'Inquired about yoga classes and female coach.',
    status: 'Enrolled',
    createdAt: '2026-10-03 18:20',
  },
];

export const initialMessages: ContactMessage[] = [
  {
    id: 'msg-1',
    fullName: 'Kamran Shah',
    phoneNumber: '03124449876',
    message: 'What are the charges for personal training sessions on weekends?',
    status: 'Replied',
    createdAt: '2026-10-04 11:20',
  },
  {
    id: 'msg-2',
    fullName: 'Sara Qureshi',
    phoneNumber: '03457778901',
    message: 'Do you have female-only hours or separate sections?',
    status: 'Unread',
    createdAt: '2026-10-05 10:45',
  },
];
